console.log(5 * 10);
var numero = 10;
console.log(numero);
var base = 5;
var altura = 10;
var area = base * altura;
console.log('El area del rectángulo es ' + area);
numero = 20;
console.log(numero);
var mensaje;
mensaje = "Hola gente";
console.log(mensaje);
console.log(typeof mensaje);
console.log(typeof area);
